#MOST FUNDAMENTAL CONCEPTS!!!


*getting info from tensors
*manipulating tensors
*tensors and numpy
*using @tf.function
*using gpus with tensorflow


In [25]:
import tensorflow as tf
import numpy as np
import tensorflow_probability as tfp

In [2]:
#creating tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#check for number of dimensions of a tensor

scalar.ndim

0

In [4]:
#create a vector

vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
#create a matrix(has more than 1 dimension)

matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [5.,9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 5.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
#lets create a tensor
tensor = tf.constant([[[1,2,3,],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                       [[13,14,15],
                        [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction
* Matrix: a 2 dimensional array of numbers
* Tensor: an n-dimensional array of numbers(when n can be any number, a 0-dimensional tensor is a scalaer, a 1-dimensional tensor in a vector)

In [12]:
changeable_tensor = tf.Variable([10,7])
unchangle_tensor = tf.constant([10,7])
changeable_tensor, unchangle_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
#lets try to cchange the elements of changeable tensor

changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
#lets try .assign()

changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
#lets try to change unchangeable tensor

unchangle_tensor[0].assign(7)
unchangle_tensor

CREATING RANDOM TENSORS

tensors of some arbitrary size which contain random numbers

In [ ]:
#create two random (but same) tensors
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))


random_2 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_2 = random_2.normal(shape=(3,2))

random_1,random_2,random_1 == random_2

In [ ]:
### shuffling the order of the values in the random tensor
#valuable whenu want to shuffle ur data

not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim

#shuffle it
tf.random.shuffle(not_shuffled, seed=42)

### creating tensors from numpy arrays
 

In [ ]:
tf.ones([10,7])

In [ ]:
tf.zeros(shape=(3,4))

In [ ]:
#numpy arrays into tensors

#main diff between numpy and tenserflow, tensors can run on a a gpu(much faster)

import numpy as np

numpy_A = np.arange(1,25, dtype=np.int32)

numpy_A

In [ ]:
#how to change it to a tensor
A = tf.constant(numpy_A, shape=(2,3,4))
A

### getting info from tensors
* Shape
* Axis or dimension
* Rank
* Size

In [ ]:
#Create a rank 4 tensor(4 dimensions)

rank_4 = tf.zeros(shape=[2,3,4,5])
rank_4

In [ ]:
rank_4.shape, rank_4.ndim, tf.size(rank_4)

In [ ]:
#Get various attributes of our tensor

print(" Datatpye of every elemen:", rank_4.dtype)
print(" shape of every elemen:", rank_4.shape)
print(" Number of dimensions of every elemen:", rank_4.ndim)
print("elements along 0 axis:", rank_4.shape[0])
print("elements along last axis:", rank_4.shape[-1])

print("Total number of elements in our tensose", tf.size(rank_4))
print("Total number of elements in our tensose", tf.size(rank_4).numpy())

### Indexing tensors

In [ ]:
some_list = [1,2,3,4]
some_list[:2]

In [ ]:
# get the first 2 elements of each dimension

rank_4[:2,:2,:2,:2]

In [ ]:
some_list[:1]

In [ ]:
#get the first element from each dimension from each index except for the final one

rank_4[:1,:1,:1,:]

In [ ]:
#CREATE A RANK 2 TENSOR(2D )

rank_2 = tf.constant([[10,7],
                      [3,4]])

rank_2

In [ ]:
# add an extra dimension to our rank_2

rank_3 = rank_2[..., tf.newaxis]
rank_3

In [ ]:
#alt to tf.newaxid

tf.expand_dims(rank_2, axis =-1)

### Manipulating tensors( tensor operations )

**Basic operations**

+, -, *, /

In [ ]:
tensor = tf.constant([[2,5], [3,8]])
tensor + 10
#original tensor doesnt change

In [ ]:
#mult
tensor *10

In [ ]:
#sub

tensor -10

In [ ]:
# We can use the tensorflow built-in function to

tf.multiply(tensor, 10) #this way it uses the gpu which makes it faster

In [ ]:
tensor
#again og tensor doesnt change

###***Matrix multiplication***

in ML matrix multiplication is the most common tensor opearation

In [ ]:
#Matrix multiplication in tensor flow

#tf.linalg.matmul

#multiplies the tensor with its self
tf.matmul(tensor,tensor)

#tensor * tensor # not same thing

In [ ]:
#Matrix multi with python operator " @"
tensor @ tensor

In [ ]:
#Create a tensor shape = (3,2)

x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

#Create another
y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
x,y

In [ ]:
#try to matrix mult tensors of same shape
x @ y
tf.matmul(x,y)

In [ ]:
#let change the shapw of Y

reshaped_y = tf.reshape(y, shape=(2,3))

In [ ]:
x @ reshaped_y

***The dot product***

Matrix mult is also referred to as the dot product.

you can perform matrix mult using:

* `tf.matmul()`
* `tf.tensordot()`

In [ ]:
x,y

In [ ]:
tf.tensordot(tf.transpose(x), y, axes=1)

In [ ]:
#Perform matrix mult between x and y (transposed)
tf.matmul(x, tf.transpose(y))

In [ ]:
#Perform matrix mult between x and y (reshaped)
tf.matmul(x,tf.reshape(y, shape=(2,3)))

In [ ]:
#Check the values of Y, reshape Y and tranpose Y
print("Normal Y:")
print(y, "/n")

print("Y reshaped to (2,3):")
print(tf.reshape(y, (2,3)), "/n")

print("Y transposed:")
print(tf.transpose(y))

In [ ]:
#Create a new tensor with default dtype(float32)
B = tf.constant([1.7,7.4])
B

### Chaning dataype of a tensor

In [ ]:
C = tf.constant([2,4])
C.dtype

In [ ]:
#Change from float32 to float16 (reduced precision)
B = tf.cast(B, tf.float16)
B,B.dtype

In [ ]:
#Change from int32 to float32
E = tf.cast(C, tf.float32)
E

### aggregating *tensors*

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [15]:
# Get the absolute values
D = tf.constant([-3,-9])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-3, -9], dtype=int32)>

In [16]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 9], dtype=int32)>

Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [19]:
#Create a random tensor with values between 0 and 100 of size 50

E = tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([13, 75, 66, 99, 62, 64, 93, 39, 18,  7, 51, 31, 48, 23, 95, 29, 50,
       29, 87, 95, 99, 26, 59, 28, 95, 10,  2, 13, 33, 82,  5, 13, 55, 52,
       61, 32, 87, 47, 48, 59, 25, 17, 90, 90, 34,  7, 58, 72, 80, 51])>

In [20]:
E.shape, E.ndim, tf.size(E)

(TensorShape([50]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [21]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [22]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [23]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [24]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2504>

In [33]:
# Find the vairance of our tensor
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=863>

In [30]:
# Find the standard deviation

tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.387644>

*** Find the positional maximum and minimum

In [35]:
# Create a new tensor for finding positional minimum and maximum

F = tf.random.uniform(shape=[50]) #1D tensor with 50 random numbers
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([5.20677090e-01, 4.48643446e-01, 6.56340241e-01, 1.04670525e-01,
       7.60245323e-02, 1.76086783e-01, 4.92915034e-01, 1.56391144e-01,
       6.80259943e-01, 5.99572778e-01, 3.31978440e-01, 7.73901463e-01,
       6.36909008e-01, 2.04520106e-01, 6.35942698e-01, 8.19956422e-01,
       4.18803692e-02, 3.36096764e-01, 5.47368646e-01, 9.23208952e-01,
       1.64169073e-01, 8.72606039e-02, 3.80374432e-01, 5.81944227e-01,
       7.60411739e-01, 8.17352533e-02, 8.59232783e-01, 1.19123101e-01,
       3.64073753e-01, 3.07616472e-01, 6.21157408e-01, 9.83438969e-01,
       5.24915457e-02, 9.61585641e-01, 6.77964568e-01, 6.00695610e-04,
       1.40885592e-01, 5.60410976e-01, 2.78716445e-01, 6.77829981e-01,
       4.24288511e-01, 8.35938215e-01, 7.81018376e-01, 9.50978518e-01,
       3.78193259e-01, 7.88563013e-01, 9.37817097e-01, 3.57561707e-01,
       4.63651180e-01, 7.66031981e-01], dtype=float32)>

In [36]:
tf.argmax(F) #returns the index of the max number from array 

<tf.Tensor: shape=(), dtype=int64, numpy=31>

In [37]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.98343897>

In [38]:
#Find the max value
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.98343897>

In [39]:
#Find min
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=35>

In [40]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0006006956>

### Squeezing a tensor( removing all single dimensions )

In [46]:
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[3.6038184e-01, 1.1789346e-01, 5.3254378e-01, 9.1040444e-01,
           6.0630238e-01, 5.5868435e-01, 9.4665229e-01, 6.1804175e-02,
           6.7064404e-01, 1.2427330e-02, 5.7114363e-03, 8.4604263e-01,
           8.6750996e-01, 4.3735194e-01, 9.9460256e-01, 5.3655148e-02,
           8.9649510e-01, 4.3087018e-01, 6.6620970e-01, 1.4880776e-01,
           2.1876752e-01, 4.5051515e-01, 5.5244076e-01, 2.2579277e-01,
           8.9887536e-01, 7.3176634e-01, 8.7610817e-01, 1.9820213e-01,
           7.2238374e-01, 4.5361245e-01, 9.4084358e-01, 9.1752279e-01,
           2.2123170e-01, 1.4142764e-01, 8.3086395e-01, 9.1004372e-04,
           5.2270222e-01, 6.0167015e-01, 9.5632422e-01, 6.1440182e-01,
           2.8847802e-01, 1.1302149e-01, 5.4589403e-01, 5.6724334e-01,
           8.5500669e-01, 7.1942902e-01, 1.6285300e-02, 9.2574251e-01,
           2.4269927e-01, 4.4171059e-01]]]]], dtype=float32)>

In [47]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [51]:
G_squeezed = tf.squeeze(G) #removes dimensions of size 1 from the tensor
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([3.6038184e-01, 1.1789346e-01, 5.3254378e-01, 9.1040444e-01,
        6.0630238e-01, 5.5868435e-01, 9.4665229e-01, 6.1804175e-02,
        6.7064404e-01, 1.2427330e-02, 5.7114363e-03, 8.4604263e-01,
        8.6750996e-01, 4.3735194e-01, 9.9460256e-01, 5.3655148e-02,
        8.9649510e-01, 4.3087018e-01, 6.6620970e-01, 1.4880776e-01,
        2.1876752e-01, 4.5051515e-01, 5.5244076e-01, 2.2579277e-01,
        8.9887536e-01, 7.3176634e-01, 8.7610817e-01, 1.9820213e-01,
        7.2238374e-01, 4.5361245e-01, 9.4084358e-01, 9.1752279e-01,
        2.2123170e-01, 1.4142764e-01, 8.3086395e-01, 9.1004372e-04,
        5.2270222e-01, 6.0167015e-01, 9.5632422e-01, 6.1440182e-01,
        2.8847802e-01, 1.1302149e-01, 5.4589403e-01, 5.6724334e-01,
        8.5500669e-01, 7.1942902e-01, 1.6285300e-02, 9.2574251e-01,
        2.4269927e-01, 4.4171059e-01], dtype=float32)>, TensorShape([50]))

### **One-hot encode Tensors**



In [53]:
# Create a list of indices

some_list = [0,1,2,3] # could be red , green, blue, purple

#One hot encode our list
tf.one_hot( some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [55]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="bananas", off_value="mago")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'bananas', b'mago', b'mago', b'mago'],
       [b'mago', b'bananas', b'mago', b'mago'],
       [b'mago', b'mago', b'bananas', b'mago'],
       [b'mago', b'mago', b'mago', b'bananas']], dtype=object)>

###  Squaring, log, square root

In [56]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [57]:
#Square it
tf.square(H) #square every value in the tensor

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [62]:
#Find the square root
tf.sqrt(tf.cast(H,dtype=tf.float32)) #doesnt accept int32, so we changed it

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [65]:
# Find the log
tf.math.log(tf.cast(H,dtype=tf.float32)) #doesnt accept int32, so we changed it

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and numpy

TensorFlow interacts extemely well with Numpy arrays

In [66]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([4.,8., 9.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4., 8., 9.])>

In [68]:
# Convert our tensor to numpy array
np.array(J), type(np.array(J))

(array([4., 8., 9.]), numpy.ndarray)

In [70]:
# Convert tensor J to a Nimpy array
J.numpy(), type(J.numpy())

(array([4., 8., 9.]), numpy.ndarray)

In [74]:
J = tf.constant([3.,0.4])
J.numpy()[1]

0.4

In [76]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,5.,7.]))
tensor_J = tf.constant([3.,5.,7.])

#check both dtypes
numpy_J.dtype, tensor_J.dtype
#float64          float32

(tf.float64, tf.float32)